### ISSUE TITLE
分割网络在android端命令行执行时报错

### ISSUE THREAD

**Issue by renshujiajia** [Digital2Slave/ncnn-android-yolov8-seg#10]
输出out0和out1的nchw都对的上，但是后续跑到decode_mask中的sigmoid函数时出现sigmentation fault问题，wiki里的这套工作流我在ubuntu 20.04 x86_64设备上能够正常推理，没有一点问题，但是在android上反倒不行了，不明白这个可能是啥原因

ndk 为 20b，api选的22，设备为rk3588 Android12

**Comment by Digital2Slave** [comment]
没有看到报错信息，无法定位具体原因，有可能是动态库的问题。

**Comment by renshujiajia** [comment]
> 没有看到报错信息，无法定位具体原因，有可能是动态库的问题。

已经解决了，问题原因是我是用的ncnn版本创建sigmoid这个pipeline时崩溃了，跟换ncnn版本测试通过。
