### ISSUE TITLE
How to improve the quality of segmentation of converted model

### ISSUE THREAD

**Issue by greg007-web** [Digital2Slave/ncnn-android-yolov8-seg#14]
I made an adaptation to take photos and perform image segmentation. When I convert the original model, I lose segmentation quality; it segments outside the object, which affects my work with measurements. Is there anything I can do to improve this quality in the code or during the conversion? Thank you.

Thanks.

**Comment by Digital2Slave** [comment]
1. refine your custom dataset label without missing.
2. fine tuning your segment model with your custom dataset.
3. set `prob_threshold` and `nms_threshold ` values according to your  measurements.
