### ISSUE TITLE
New version differences compolicated conversion for onnx

### ISSUE THREAD

**Issue by greg007-web** [Digital2Slave/ncnn-android-yolov8-seg#9]
How I modify modules.py in ultralytics==8.0.196, I did not find this file (modules.py) in nn folder in the last version?
 In ultralytics==8.0.40 it's works well for me but in the new version it's a problem.

**Comment by Digital2Slave** [comment]
https://github.com/Digital2Slave/ncnn-android-yolov8-seg/wiki/Convert-yolov8%E2%80%90seg-to-ncnn-model-step-by-step
